### ISSUE TITLE
Release v0.0.3 ?

### ISSUE THREAD

**Issue by jose-lpa** [mishagrol/pyRothC#5]
Hello,

Would be possible to release a new version with the last changes added after v0.0.2? Or are some things still missing that you would like to add to a release?

Thank you.

**Comment by mishagrol** [comment]
@jose-lpa yes, shure, I will add tomorrow!)

**Comment by jose-lpa** [comment]
Thank you @mishagrol , much appreciated :slightly_smiling_face: I will close this issue then.
