### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jose-lpa** [mishagrol/pyRothC#8]
Could be possible to have a new release, for the last changes added in PR #7 ?

Many thanks in advance.

PS: I have been using [`tbump`](https://github.com/your-tools/tbump) for version bumping in some projects, and found it very useful to create the bump commits and make the changes to the version number, if you want to try :slightly_smiling_face:

**Comment by mishagrol** [comment]
@jose-lpa hello! Yes, I will release your changes next week. I have an idea, may be to add some weather provider to package? For example, use NASA POWER API to recieve weather for RothC model by coordinates

**Comment by jose-lpa** [comment]
Hi, I'm not sure if it makes sense to embed connections to 3rd party APIs in this package. I believe this should be for the RothC calculations only, data provider agnostic. And let the users implement the data acquisition as they want or need.

**Comment by mishagrol** [comment]
> Hi, I'm not sure if it makes sense to embed connections to 3rd party APIs in this package. I believe this should be for the RothC calculations only, data provider agnostic. And let the users implement the data acquisition as they want or need.

Shure, thank you! Added version 0.0.4 to pypi!)

**Comment by mishagrol** [comment]
new version added to pypi
